### ISSUE TITLE
TODOs for mutation

### ISSUE THREAD

**Issue by done-4u** [prosyslab/optimuzz#22]
# TODO
- [x] 플래그 (예: `nsw`) 추가/변경/제거
- [ ] 명령/블록 제거
- [ ] 명령 종류 추가 (예: `select`, `switch`)
  - [x] `i32` 외 정수 타입 추가 및 형변환 명령 처리
  - [x] 포인터 추가 및 메모리 명령 처리
- [ ] 확률 조정
- [ ] 정수 너머로 정의역 확장 (예: 실수, 벡터, 구조체 등)
- [ ] Basicblock CFG 수정

# Not Planning
- 함수 개수 1개 → 그 이상
